apiVersion: v1
kind: Service
metadata:
  name: hello-world-no-selector
spec:
  ports:
    - protocol: TCP
      port: 8080
     

---

apiVersion: v1
kind: Endpoints
metadata:
  name: hello-world-no-selector
subsets:
  - addresses:
      - ip: 10.0.0.135
    ports:
      - port: 30074